### PR TITLE
Remove client_unix/client_test.ml (now elsewhere)

### PR DESCRIPTION
**Pull request by thomassa**
This source file has not been compiled in this repository since
Anil's change in July 2013 to fix a circular dependency:
"Fix build cycle between xenstore and xenstore_transport"

Recently I copied the file from here to the ocaml-xenstore-clients
repository, and it is being built there now. Therefore it can be
deleted from here.

### CODE REVIEW

**Comment by mseri** [comment]
Let's finalise the move then (I would be happy to merge this, but it seems that I can't)

**Comment by thomassa** [comment]
It seems I lack the relevant privilege on this repository, too!

**Comment by thomassa** [comment]
I've just noticed that this repository is a fork of the mirage one, and is fourteen commits behind.
We might want to catch up at some point. In the mean time I shall submit the change upstream as well...

**Comment by euanh** [comment]
@thomassa We build ocaml-xenstore from the mirage repository.   This repository is not used any more.
See https://github.com/xenserver/xen-api-base-specs/blob/master/SPECS/ocaml-xenstore.spec

**Pull request closed without merging**
